sudo: required
services:
  - docker

before_install:
  - docker build -t simon/react-ex -f Dockerfile.dev .

script: 
   - docker run -e CI=true simon/react-ex npm run test 


deploy: 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "poc-react-ex"
  env: "PocReactEx-env"
  bucket_name: "elasticbeanstalk-eu-west-1-718038347277"
  bucket_path: "poc-react-ex"
  on:
    branch: master


  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  