version: '3'
services: 
  react-example:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3025:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    
    